//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddToSurvey
    {
        public int Id { get; set; }
        public string Id_interviewer { get; set; }
        public Nullable<int> Id_survey { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
