//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineAnswer
    {
        public int id { get; set; }
        public string answer_text { get; set; }
        public Nullable<int> id_question { get; set; }
    
        public virtual OnlineQuestion OnlineQuestion { get; set; }
    }
}
